### ISSUE TITLE
error  - AttributeError: 'Namespace' object has no attribute 'world'

### ISSUE THREAD

**Issue by WindNinja** [alexivkin/wifipicket#3]
any idea why this happens?

root@kali:~/Downloads/wifipicket-master# python -u wifipicket.py
[*] Packet filter: (not type ctl) and (not type mgt subtype deauth)
[*] Finding the most powerful interface...
[+] Starting monitor mode on wlan0
[*] wlan0 - 6e:02:2r:e0:4b:00
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "wifipicket.py", line 145, in channel_hop
    maxChan = 11 if not args.world else 13
AttributeError: 'Namespace' object has no attribute 'world'

[!] Exception while sniffing. 'Namespace' object has no attribute 'world':<type 'exceptions.AttributeError'>
Traceback (most recent call last):
  File "wifipicket.py", line 523, in <module>
    sniff(iface=mon_iface, store=0, prn=cb, filter=bpf)
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 944, in sniff
    r = prn(p)
  File "wifipicket.py", line 331, in cb
    APs_add(clients_APs, APs, pkt, args.channel, args.world)
AttributeError: 'Namespace' object has no attribute 'world'
[!] 2 attempts left.
[!] Exception while sniffing. 'Namespace' object has no attribute 'world':<type 'exceptions.AttributeError'>
Traceback (most recent call last):
  File "wifipicket.py", line 523, in <module>
    sniff(iface=mon_iface, store=0, prn=cb, filter=bpf)
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 944, in sniff
    r = prn(p)
  File "wifipicket.py", line 331, in cb
    APs_add(clients_APs, APs, pkt, args.channel, args.world)
AttributeError: 'Namespace' object has no attribute 'world'
[!] 1 attempts left.
[!] Exception while sniffing. 'Namespace' object has no attribute 'world':<type 'exceptions.AttributeError'>
Traceback (most recent call last):
  File "wifipicket.py", line 523, in <module>
    sniff(iface=mon_iface, store=0, prn=cb, filter=bpf)
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 944, in sniff
    r = prn(p)
  File "wifipicket.py", line 331, in cb
    APs_add(clients_APs, APs, pkt, args.channel, args.world)
AttributeError: 'Namespace' object has no attribute 'world'
[!] 0 attempts left.
[!] Shutting down.

**Comment by Gawrisch** [comment]
having the same issue
